backend:
  name: github
  repo: kcvgan/kcygan.dev # Path to your GitHub repository

media_folder: "src/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src/content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "path", name: "path", widget: "string" }
      - { name: body, label: Body, widget: markdown }
